name: Build MediaPipe

on:
  workflow_dispatch:

jobs:

  mediapipe:
    name: Build MediaPipe
    runs-on: ubuntu-latest
    container: debian:bookworm
    defaults:
      run:
        shell: bash
    steps:

    - name: Install dependencies
      run: |
        apt-get update
        apt install -y git cmake clang-16 libegl-dev libgles-dev python3 patchelf
        apt install -y apt-transport-https curl gnupg
#software-properties-common
    
#    - name: Install GCC 13
#      run: |
#        add-apt-repository ppa:ubuntu-toolchain-r/test
#        apt update
#        apt install -y gcc-13 g++-13 binutils
#        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 13
#        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 13

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build OpenCV
      run: ./bz-local/build-opencv.sh

    - name: Add Bazel repository
      run: |
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
        mv bazel-archive-keyring.gpg /usr/share/keyrings
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list

    - name: Install Bazel
      run: |
        apt update
        apt install -y bazel-7.4.1

    - name: Build MediaPipe
      run: ./bz-local/build-mediapipe.sh

    - name: Create distributable folder
      run: |
        mkdir dist
        cp -L bazel-bin/mediapipe/tasks/c/libmediapipe.so opencv_local/build/install/lib/libopencv_*.so.414 dist

    - name: Patch OpenCV rpath
      run: patchelf --set-rpath ./lib dist/libopencv*

    - name: Export complete build
      uses: actions/upload-artifact@v4
      with:
        name: mediapipe
        path: dist
        if-no-files-found: error
        retention-days: 1
        compression-level: 1
        overwrite: true
